"""Offline nested Finder capability check. Uses throwaway browser storage only."""
import sys,threading,json,csv,io
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from integration.news_api import create_app
from werkzeug.serving import make_server
from playwright.sync_api import sync_playwright
O='http://localhost:8782';app=create_app(authorize=lambda r:True);server=make_server('127.0.0.1',8782,app);threading.Thread(target=server.serve_forever,daemon=True).start()
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/google-chrome',headless=True,args=['--no-sandbox']);context=b.new_context(viewport={'width':1440,'height':1000},accept_downloads=True,permissions=['clipboard-read','clipboard-write']);page=context.new_page();errors=[];outside=[];csp=[];context.add_init_script("window.addEventListener('securitypolicyviolation',e=>console.error('CSP_VIOLATION '+e.violatedDirective))");page.on('console',lambda m:csp.append(m.text) if 'CSP_VIOLATION' in m.text or 'Content Security Policy' in m.text else None);page.on('pageerror',lambda e:errors.append(str(e)));page.route('**/*',lambda r:r.continue_() if r.request.url.startswith(O+'/') else (outside.append(r.request.url),r.abort()))
 page.goto(O+'/workspace');page.locator('[data-view=finder]').click();page.locator('#finder').evaluate("e=>e.src='/workspace/finder/index.html#code=0:090121'");f=page.frame_locator('#finder');f.locator('#d-fav').wait_for();assert 'Coffee; roasted, not decaffeinated' in f.locator('body').inner_text();f.locator('#d-fav').click();f.locator('#d-short').click();f.get_by_text('Your note',exact=True).click();f.locator('#d-note').fill('=1+2 <script>literal</script>');f.locator('#d-note').dispatch_event('change');f.locator('#d-copy').click();copy_status=f.locator('#d-copy').inner_text();print('copy status',copy_status)
 clip=page.evaluate('navigator.clipboard.readText()');assert clip==O+'/workspace/finder/index.html#code=0:090121',clip
 page.reload();page.locator('[data-view=finder]').click();page.locator('#finder').evaluate("e=>e.src='/workspace/finder/index.html#code=0:090121'");f=page.frame_locator('#finder');f.locator('#d-back').wait_for();assert 'Saved' in f.locator('#d-fav').inner_text();f.locator('#d-back').click();f.locator('#open-sl').click();assert '=1+2 <script>literal</script>' in f.locator('body').inner_text();assert f.locator('.sl-note script').count()==0
 with page.expect_download() as d:f.locator('#sl-csv').click()
 d.value.save_as('/downloads/finder-nested-fixture.csv');data=Path('/downloads/finder-nested-fixture.csv').read_text(encoding='utf-8-sig');r=list(csv.DictReader(io.StringIO(data)))[0];assert r['Note']=="'=1+2 <script>literal</script>";assert r['Code'].replace('.','')=='090121'
 frame=next(x for x in page.frames if '/workspace/finder/index.html' in x.url);f.locator('#sl-print').evaluate('e=>{window.fixturePrintCalls=0;window.print=()=>window.fixturePrintCalls++}');f.locator('#sl-print').click();assert f.locator('#sl-print').evaluate('e=>window.fixturePrintCalls')==1
 page.screenshot(path='/downloads/finder-nested-shortlist-desktop.png',full_page=True);page.set_viewport_size({'width':390,'height':844});mobile_outer=page.evaluate('document.documentElement.scrollWidth<=innerWidth');mobile_inner=f.locator('body').evaluate('e=>({width:innerWidth,scroll:document.documentElement.scrollWidth})');assert mobile_outer and mobile_inner['scroll']<=mobile_inner['width'];region=f.locator('.finder-shortlist-scroll');remove=f.get_by_text('Remove',exact=True);before=region.evaluate('(e)=>({scroll:e.scrollWidth,client:e.clientWidth,right:e.getBoundingClientRect().right})');rb=remove.bounding_box();box=region.bounding_box();assert before['scroll']>before['client'];assert rb['x']+rb['width']>box['x']+box['width'];f.locator('#sl-print').focus();f.locator('#sl-print').press('Tab');assert region.evaluate('e=>document.activeElement===e');region.press('End');region.press('ArrowRight');page.wait_for_timeout(350);assert region.evaluate('e=>e.scrollLeft')>0;rb=remove.bounding_box();box=region.bounding_box();assert rb['x']>=box['x'] and rb['x']+rb['width']<=box['x']+box['width']+1;page.screenshot(path='/downloads/finder-nested-shortlist-mobile.png',full_page=True)
 assert csp and all('connect-src' in m or ('Frankfurter' in m or 'frankfurter' in m) for m in csp);assert not any('script-src' in m or 'style-src' in m for m in csp);print(json.dumps({'csp_violations':csp,'keyboard_scroll':True,'nested_code':True,'copy_link':clip,'favourite_note_persistence':True,'download_csv':True,'print_invocation_fixture':True,'mobile_outer_no_overflow':mobile_outer,'mobile_inner_dimensions':mobile_inner,'errors':errors,'blocked_external_attempts':outside}));b.close()
server.shutdown()
