import sys,threading,json
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from integration.news_api import create_app
from werkzeug.serving import make_server
from playwright.sync_api import sync_playwright
rows={'geo':[{'url':'https://example.com/a','title':'Baseline fixture','country':'India'}],'brics':[]};app=create_app(reader=lambda:rows,authorize=lambda r:True);server=make_server('127.0.0.1',8774,app);threading.Thread(target=server.serve_forever,daemon=True).start()
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/google-chrome',headless=True,args=['--no-sandbox']);page=b.new_page(viewport={'width':1440,'height':980});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.route('**/*',lambda r:r.continue_() if r.request.url.startswith('http://127.0.0.1:8774/') else r.abort())
 page.goto('http://127.0.0.1:8774/workspace/countries');page.locator('#country-label').fill('India');page.get_by_role('button',name='Load country',exact=True).click();page.get_by_text('This country is not watched. No update comparison.',exact=True).wait_for();page.get_by_role('button',name='Add to watchlist').click();page.get_by_role('button',name='Load country',exact=True).click();page.wait_for_function("() => document.getElementById('watch-update-status').textContent.startsWith('First supplied-view baseline set.')")
 rows['geo'].append({'url':'https://example.com/b','title':'Newly seen fixture <img src=x>','country':'India'});page.get_by_role('button',name='Load country',exact=True).click();page.wait_for_function("() => document.getElementById('watch-update-status').textContent.startsWith('1 newly seen')");assert page.locator('#watch-update-items img').count()==0;page.screenshot(path='/downloads/watch-updates-desktop.png',full_page=True);page.set_viewport_size({'width':390,'height':844});page.screenshot(path='/downloads/watch-updates-mobile.png',full_page=True);assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
 page.reload();page.get_by_role('button',name='India',exact=True).click();page.wait_for_function("() => document.getElementById('watch-update-status').textContent.startsWith('0 newly seen')");assert page.locator('#watch-update-items p').count()==0
 page.locator('#country-project').select_option('geo');page.get_by_role('button',name='Load country',exact=True).click();page.wait_for_function("() => document.getElementById('watch-update-status').textContent.startsWith('First supplied-view baseline set.')")
 page.evaluate("() => {Storage.prototype.setItem=function(){throw Error('blocked')}}");rows['geo'].append({'url':'https://example.com/c','title':'Unsaved update fixture','country':'India'});page.get_by_role('button',name='Load country',exact=True).click();page.wait_for_function("() => document.getElementById('watch-update-status').textContent.includes('baseline not saved')");assert '1 newly seen' in page.locator('#watch-update-status').inner_text();assert not errors;print(json.dumps({'errors':errors,'first_baseline_silent':True,'new_identity_visible':True,'reload_no_repeat':True,'project_baseline_separate':True,'failed_persistence_explicit':True,'mobile_no_overflow':True}));b.close()
server.shutdown()
