import sys,threading,json
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from integration.news_api import create_app
from werkzeug.serving import make_server
from playwright.sync_api import sync_playwright
app=create_app(authorize=lambda r:True);server=make_server('127.0.0.1',8779,app);threading.Thread(target=server.serve_forever,daemon=True).start()
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/google-chrome',headless=True,args=['--no-sandbox']);context=b.new_context(viewport={'width':390,'height':844});page=context.new_page();errors=[];requests=[];page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda r:requests.append(r.url))
 page.goto('http://127.0.0.1:8779/workspace/finder/index.html#code=0:090121');page.locator('#d-fav').wait_for();assert page.evaluate('navigator.serviceWorker.getRegistrations().then(r=>r.length)')==0
 page.locator('#finder-offline-save').click();page.locator('#finder-offline-status').filter(has_text='Public snapshot stored').wait_for(timeout=40000);assert page.evaluate('caches.keys()')==['geo-public-finder-cfc66f0e2234-v1'];keys=page.evaluate('caches.open("geo-public-finder-cfc66f0e2234-v1").then(c=>c.keys()).then(rs=>rs.map(r=>r.url))');assert keys==['http://127.0.0.1:8779/workspace/finder/offline.html'];assert not any('/api/' in x for x in keys)
 awaitable=page.evaluate('localStorage.setItem("hsn-api-key","PRIVATE-DEVICE-KEY");localStorage.setItem("hsn-notes",JSON.stringify({"0:090121":"PRIVATE-DEVICE-NOTE"}));true')
 page.wait_for_function('navigator.serviceWorker.controller!==null');requests.clear();context.set_offline(True);page.goto('http://127.0.0.1:8779/workspace/finder/offline.html#code=0:090121');page.locator('#d-fav').wait_for(timeout=40000);print('DETAIL', 'Coffee; roasted, not decaffeinated' in page.inner_text('body'),'KEY',repr(page.evaluate('V.apiKey')),'NOTES',page.evaluate('JSON.stringify(V.notes)'),'WIDTH',page.evaluate('[document.documentElement.scrollWidth,innerWidth]'));assert 'Coffee; roasted, not decaffeinated' in page.inner_text('body');assert page.evaluate('V.apiKey')=='';assert page.evaluate('JSON.stringify(S.notes)')=='{}';assert 'PRIVATE-DEVICE-KEY' not in page.content();assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.screenshot(path='/downloads/finder-public-offline-mobile.png',full_page=True);page.screenshot(path='/downloads/finder-public-offline-viewport.png');assert not any('/api/' in x or not x.startswith('http://127.0.0.1:8779/') for x in requests)
 context.set_offline(False);page.goto('http://127.0.0.1:8779/workspace/finder/index.html');page.locator('#finder-offline-clear').click();page.locator('#finder-offline-status').filter(has_text='cleared').wait_for();assert page.evaluate('caches.keys()')==[];assert page.evaluate('navigator.serviceWorker.getRegistrations().then(rs=>rs.length)')==0;assert not errors,errors;print(json.dumps({'default_no_worker':True,'explicit_save_clear':True,'cache_keys':keys,'offline_code_details':True,'provider_keys_and_notes_not_read':True,'private_paths_not_cached':True,'errors':errors}));b.close()
server.shutdown()
