import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';
import {coverage,completeRows} from '../../updater_runtime/comtrade-publication.mjs';
const root=process.cwd(),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'comtrade178-'));process.chdir(tmp);process.env.COMTRADE_KEY='fixture';delete process.env.RENDER_DRY;globalThis.setTimeout=f=>{queueMicrotask(f);return 1;};
fs.mkdirSync('src');fs.mkdirSync('state');fs.writeFileSync('src/tradevalues.ts',"// calendar year 2025\n'123456': [10, 20]\n'234567': [5, 10]\n");
const reply=(data,status=200)=>({ok:status===200,status,json:async()=>data});
try {
 assert.throws(()=>coverage([],[]));assert.throws(()=>completeRows({data:[],count:2}));assert.throws(()=>completeRows({data:[],count:'0'}));assert.deepEqual(coverage([1,2],[1,1]),{complete:false,expected:2,completed:1,missing:[2],throttled:false,published:false});
 for(const [file,fn,out]of [['market','bakeMarket','marketdata'],['marketx','bakeMarketX','marketexp']]){
  const m=await import(pathToFileURL(path.join(root,'comtrade-'+file+'.mjs')));const state='state/comtrade-'+file+'.json',output='src/'+out+'.ts';fs.writeFileSync(output,'last-good');
  let batch=0;globalThis.fetch=async u=>u.includes('partnerAreas')?reply({results:Array.from({length:16},(_,i)=>({id:i+1,text:'Country'+(i+1),isGroup:false}))}):++batch===1?reply({data:[{cmdCode:'123456',primaryValue:99,reporterCode:1}],count:1}):reply({},429);
  let r=await m[fn]();assert.equal(r.complete,false);assert.equal(r.published,false);assert.equal(r.throttled,true);assert.deepEqual(r.missing,[16]);assert.equal(fs.readFileSync(output,'utf8'),'last-good');let st=JSON.parse(fs.readFileSync(state));st.failures[16]=3;fs.writeFileSync(state,JSON.stringify(st));
  let requested=[];globalThis.fetch=async u=>{if(u.includes('partnerAreas'))return reply({results:Array.from({length:16},(_,i)=>({id:i+1,text:'Country'+(i+1),isGroup:false}))});requested.push(u);return reply({data:[{cmdCode:'123456',primaryValue:100,reporterCode:16}],count:1});};
  r=await m[fn]();assert.equal(r.complete,true);assert.equal(r.published,true);assert.equal(requested.length,1);assert.match(fs.readFileSync(output,'utf8'),/Country16/);assert.equal(JSON.parse(fs.readFileSync(state)).failures[16],undefined);
  // Reference growth must hold old output rather than claiming complete.
  const last=fs.readFileSync(output);globalThis.fetch=async u=>u.includes('partnerAreas')?reply({results:[...Array.from({length:16},(_,i)=>({id:i+1,text:'Country'+(i+1)})),{id:17,text:'New'}]}):reply({},429);r=await m[fn]();assert.equal(r.complete,false);assert.deepEqual(r.missing,[17]);assert.deepEqual(fs.readFileSync(output),last);
  // Truncated batch and individual retry must not be marked done or published.
  fs.unlinkSync(state);globalThis.fetch=async u=>u.includes('partnerAreas')?reply({results:[{id:1,text:'One'}]}):reply({data:[],count:1});r=await m[fn]();assert.equal(r.complete,false);assert.equal(r.failed,1);assert.deepEqual(JSON.parse(fs.readFileSync(state)).done,[]);assert.deepEqual(fs.readFileSync(output),last);
 }
 // Partners: complete trend table is independent; incomplete partners never publish.
 const partners=await import(pathToFileURL(path.join(root,'comtrade-partners.mjs')));fs.writeFileSync('src/tradepartners.ts','last-partners');fs.writeFileSync('src/tradetrend.ts','last-trend');let codeCalls=0;
 globalThis.fetch=async u=>{if(u.includes('partnerAreas'))return reply({results:[{PartnerCode:1,PartnerDesc:'One'}]});if(u.includes('cmdCode=AG6'))return reply({data:[{cmdCode:'123456',primaryValue:10}],count:1});if(u.includes('cmdCode=123456'))return reply({data:[],count:0});codeCalls++;return reply({},429);};
 let r=await partners.bakePartners();assert.equal(r.complete,false);assert.equal(r.published,false);assert.equal(r.throttled,true);assert.deepEqual(r.missing,['234567']);assert.equal(fs.readFileSync('src/tradepartners.ts','utf8'),'last-partners');assert.ok(codeCalls>0);
 let st=JSON.parse(fs.readFileSync('state/comtrade-partners.json'));st.failures['234567']=8;fs.writeFileSync('state/comtrade-partners.json',JSON.stringify(st));globalThis.fetch=async u=>u.includes('partnerAreas')?reply({results:[]}):reply({data:[],count:0});r=await partners.bakePartners();assert.equal(r.complete,true);assert.equal(r.published,true);assert.match(fs.readFileSync('src/tradepartners.ts','utf8'),/'234567'/);
 // Mirror: explicit done supports a valid empty dataset; failed>=3 remains retryable.
 fs.writeFileSync('src/marketdata.ts','export const MARKET_DATA_YEAR = 2025;');fs.writeFileSync('src/mirrordata.ts','last-mirror');const mirror=await import(pathToFileURL(path.join(root,'comtrade-mirror.mjs')));let n=0;globalThis.fetch=async()=>++n===1?reply({data:[],count:0}):reply({},429);r=await mirror.bakeMirror();assert.equal(r.complete,false);assert.equal(r.published,false);assert.equal(fs.readFileSync('src/mirrordata.ts','utf8'),'last-mirror');st=JSON.parse(fs.readFileSync('state/comtrade-mirror.json'));assert.deepEqual(st.done,['Russia']);st.failures.Iran=9;fs.writeFileSync('state/comtrade-mirror.json',JSON.stringify(st));n=0;globalThis.fetch=async()=>{n++;return reply({data:[],count:0});};r=await mirror.bakeMirror();assert.equal(r.complete,true);assert.equal(r.published,true);assert.equal(n,22);assert.equal(JSON.parse(fs.readFileSync('state/comtrade-mirror.json')).failures.Iran,undefined);
 assert.equal(fs.readdirSync('state').filter(f=>f.endsWith('.pending')).length,0);console.log('Comtrade178 partial429/lastgood/resume/failure>=3/referencegrowth/truncation/partners/mirrorempty/fences PASS; all fetches mocked');
} finally{process.chdir(root);fs.rmSync(tmp,{recursive:true,force:true});}
