/* Fixture UI only. No localStorage, caller token fields or automatic polling. */
'use strict';
const el=id=>document.getElementById(id);let csrf='',preauth='',version=0,busy=false;
async function api(path,method='GET',body){const r=await fetch(path,{method,credentials:'same-origin',cache:'no-store',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});let data;try{data=await r.json();}catch{throw new Error('Fixture response unavailable');}if(!r.ok)throw new Error(data.error||'Fixture request refused');return data;}
function lock(on){busy=on;for(const b of document.querySelectorAll('button'))b.disabled=on;}
async function operation(fn){if(busy)return;lock(true);try{await fn();}catch(e){el('status').textContent=e.message;}finally{lock(false);}}
async function loadPreauth(){const d=await api('/account/preauth');preauth=d.csrf;}
async function loadSettings(){const d=await api('/account/settings');const s=d.settings;version=s.version;el('channels').value=s.channels.filter(c=>c.compulsory!==true).map(c=>c.name+' | '+c.video).join('\n');el('watchlist').value=s.watchlist.join('\n');el('version').textContent='Fixture revision '+version;}
async function signedIn(){const d=await api('/account/whoami');csrf=d.csrf;el('identity').textContent=d.username+' - fixture settings';await loadSettings();el('settings').hidden=false;el('login').hidden=true;}
el('login').onsubmit=e=>{e.preventDefault();operation(async()=>{const password=el('password').value;el('password').value='';try{await api('/account/login','POST',{username:el('username').value,password,csrf:preauth});await signedIn();el('status').textContent='Signed in to this memory-only fixture.';}catch(e){await loadPreauth();throw e;}});};
el('save').onclick=()=>operation(async()=>{const lines=el('channels').value.split('\n').filter(x=>x.trim());const channels=lines.map(line=>{const parts=line.split('|');if(parts.length!==2)throw new Error('Use name | video ID, one channel per line.');return {name:parts[0].trim(),video:parts[1].trim()};});const watchlist=el('watchlist').value.split('\n').map(x=>x.trim()).filter(Boolean);await api('/account/save-settings','POST',{csrf,channels,watchlist,version});await loadSettings();el('status').textContent='Saved to the memory-only fixture. Not shared with the merged app.';});
el('reload').onclick=()=>operation(async()=>{await loadSettings();el('status').textContent='Loaded saved fixture settings. Unsaved edits discarded.';});
el('export').onclick=()=>operation(async()=>{const d=await api('/account/export','POST',{csrf});const url=URL.createObjectURL(new Blob([JSON.stringify(d.data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='fixture-account.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);el('status').textContent='Downloaded fixture account. No password or session token included.';});
el('logout').onclick=()=>operation(async()=>{await api('/account/logout','POST',{csrf});csrf='';el('channels').value='';el('watchlist').value='';el('settings').hidden=true;el('login').hidden=false;await loadPreauth();el('status').textContent='Signed out.';});
operation(async()=>{await loadPreauth();try{await signedIn();el('status').textContent='Existing fixture session loaded.';}catch(e){el('status').textContent='Ready for a test account. Never use a real password.';}});
