"""Injected Geo snapshot/export adapter. No URI, client creation or route.

Independent source/index permission review remains a prerequisite. Snapshot
session and full sort-key scan close the sample-only schema gap locally; fake
session tests do not prove the actual server's index, snapshot or access state.
"""
import time,math,json
from bson import ObjectId
from .keyset_plan import query_plan,resume,page_resume,ORDER
from .raw_pager import RawPager
from .original_stream import OriginalStream

class SnapshotUnavailable(ValueError):pass
class GeoSnapshot:
 def __init__(self,client,*,review,clock=time.monotonic):
  # No effects until source review is exact, closed and plain.
  fields={'mapping','read_only','snapshot_supported','index','index_explain_verified'}
  if type(review) is not dict or set(review)!=fields or review.get('mapping')!=('geo_intel','articles') or review.get('read_only') is not True or review.get('snapshot_supported') is not True or review.get('index_explain_verified') is not True:raise SnapshotUnavailable('Explicit Geo export source review required')
  index=review['index']
  if type(index) is not str or not 1<=len(index)<=128 or not all(c.isascii() and (c.isalnum() or c in '_-') for c in index) or not callable(clock):raise SnapshotUnavailable('Explicit bounded index and clock required')
  self._session=None;self._collection=None;self._closed=False;self._verified=False;self._after=None
  self._index=index;self._clock=clock
  failed=False
  try:
   self._start=clock()
   self._session=client.start_session(snapshot=True,causal_consistency=False)
   if self._session is None:raise ValueError()
   self._collection=client['geo_intel']['articles']
  except BaseException:
   self.close();failed=True
  if failed:raise SnapshotUnavailable('Geo export snapshot unavailable')
 def _deadline(self):
  elapsed=self._clock()-self._start
  if not math.isfinite(elapsed) or not 0<=elapsed<=120:raise SnapshotUnavailable('Geo export time budget exceeded')
 def _cursor(self,query,projection,limit=None):
  self._deadline();cursor=None
  try:
   cursor=self._collection.find(query,projection,session=self._session,collation={'locale':'simple'})
   cursor.sort(list(ORDER['geo']));cursor.hint(self._index);cursor.max_time_ms(2000);cursor.batch_size(100)
   if limit is not None:cursor.limit(limit)
   return cursor
  except BaseException:
   if cursor is not None:
    try:cursor.close()
    except Exception:pass
   raise
 def verify_scope(self,project,order):
  cursor=None;failed=False
  try:
   if self._closed or self._verified or type(project) is not str or project!='geo' or type(order) is not tuple or order!=ORDER['geo']:raise ValueError()
   # Exhaust all records, not a typed $match/count that silently hides legacy
   # data. Same session and binary collation as continuation pages.
   cursor=self._cursor({}, {'score':1,'published':1,'_id':1})
   previous=None
   for row in cursor:
    self._deadline()
    if type(row) is not dict or set(row)!={'score','published','_id'}:raise ValueError()
    current=resume('geo',row)
    if previous is not None and not current.values<previous.values:raise ValueError()
    previous=current
   self._deadline();self._verified=True
  except BaseException:
   if cursor is not None:
    try:cursor.close()
    except Exception:pass
    cursor=None
   self.close();failed=True
  finally:
   if cursor is not None:
    try:cursor.close()
    except Exception:pass
  if failed:raise SnapshotUnavailable('Geo export schema snapshot unavailable')
  return True
 def execute(self,plan):
  cursor=None;failed=False
  try:
   if self._closed or not self._verified or type(plan) is not dict or plan.get('project')!='geo':raise ValueError()
   # Only the closed original plan shape generated by reviewed RawPager.
   if set(plan)!=set(query_plan('geo')) or plan['sort']!=list(ORDER['geo']) or plan['projection']!=query_plan('geo')['projection'] or type(plan['limit']) is not int or not 1<=plan['limit']<=1000 or plan['max_time_ms']!=2000:raise ValueError()
   expected=query_plan('geo',self._after,plan['limit'])
   if plan!=expected:raise ValueError()
   cursor=self._cursor(expected['query'],expected['projection'],expected['limit'])
   rows=[];size=2
   for row in cursor:
    self._deadline()
    if len(rows)>=plan['limit'] or type(row) is not dict or not set(row)<=set(plan['projection']):raise ValueError()
    # Before append/JSON copying: provider returns at most16MiB BSON but
    # retain only bounded scalars/list fields, not unbounded materialized pages.
    for k,v in row.items():
     if k=='_id' and type(v) is ObjectId:continue
     if type(v) is str and len(v)<=32000:continue
     if v is None or type(v) in (int,float,bool):continue
     if k=='corroborated_by' and type(v) is list and len(v)<=100 and all(type(x) is str and len(x)<=8000 for x in v):continue
     raise ValueError()
    size+=len(json.dumps(row,ensure_ascii=False,allow_nan=False,separators=(',',':'),default=lambda v:str(v) if type(v) is ObjectId else None).encode('utf-8'))+1
    if size>2*1024*1024:raise ValueError()
    rows.append(row)
   self._deadline();self._after=page_resume('geo',rows,self._after,limit=plan['limit'])
  except BaseException:
   if cursor is not None:
    try:cursor.close()
    except Exception:pass
    cursor=None
   self.close();failed=True
  finally:
   if cursor is not None:
    try:cursor.close()
    except Exception:pass
  if failed:raise SnapshotUnavailable('Geo export page unavailable')
  return rows
 def close(self):
  if self._closed:return
  self._closed=True;s=self._session;self._session=None;self._collection=None
  if s is not None:
   try:s.end_session()
   except Exception:pass

class ManagedGeoStream:
 """Own the exact original stream AND session, including unstarted close."""
 def __init__(self,stream,snapshot):self._stream=stream;self._snapshot=snapshot;self.headers=dict(stream.headers);self.headers['X-Export-Scope']='injected_geo_snapshot_capped_source_review_required';self._closed=False
 def __iter__(self):return self
 def __next__(self):
  if self._closed:raise StopIteration
  try:return next(self._stream)
  except BaseException:self.close();raise
 def close(self):
  if self._closed:return
  self._closed=True
  try:self._stream.close()
  finally:self._snapshot.close()
 def __enter__(self):return self
 def __exit__(self,*args):self.close()
 @property
 def state(self):return dict(self._stream.state)

def create_geo_original_stream(client,*,review,args=None,stamp='20000101_000000',clock=time.monotonic):
 snapshot=GeoSnapshot(client,review=review,clock=clock)
 pager=None;failed=False
 try:
  pager=RawPager('geo',snapshot.execute,snapshot.verify_scope)
  remaining=120-(clock()-snapshot._start)
  if not math.isfinite(remaining) or not 0<remaining<=120:raise SnapshotUnavailable('Geo export time budget exceeded')
  stream=OriginalStream(pager,'geo',args,stamp=stamp,clock=clock,max_seconds=remaining)
  return ManagedGeoStream(stream,snapshot)
 except BaseException:
  if pager is not None:pager.close()
  snapshot.close();failed=True
 if failed:raise SnapshotUnavailable('Geo export unavailable')
