'use strict';
const assert=require('node:assert/strict'),{policy}=require('../../proxy_runtime/cors-policy.cjs');
function call(p,origin,method='GET',extra={},raw=[]){let h={};const result=p.check({method,headers:{...(origin===undefined?{}:{origin}),...extra},rawHeaders:raw},{setHeader:(k,v)=>h[k]=v});return {result,h};}
let p=policy();assert.equal(call(p,'https://fixture.example').result.status,403);assert.equal(call(p,undefined).result,null);assert.equal(call(p,undefined).h['Access-Control-Allow-Origin'],undefined);
p=policy('https://fixture.example,https://second.example:8443');let d=call(p,'https://fixture.example');assert.equal(d.result,null);assert.equal(d.h['Access-Control-Allow-Origin'],'https://fixture.example');assert.equal(d.h.Vary,'Origin');assert.equal(d.h['Access-Control-Allow-Credentials'],undefined);
for(const origin of ['null','https://evil.example','https://fixture.example/','https://fixture.example.evil','https://fixture.example,https://evil.example',['https://fixture.example']])assert.equal(call(p,origin).result.status,403);
assert.equal(call(p,'https://fixture.example','GET',{},['Origin','https://fixture.example','origin','https://fixture.example']).result.status,403);
d=call(p,'https://fixture.example','OPTIONS',{'access-control-request-method':'POST','access-control-request-headers':'Content-Type, x-app-token'});assert.equal(d.result.status,204);assert.equal(d.h['Access-Control-Allow-Methods'],'POST');assert.equal(d.h['Access-Control-Allow-Headers'],'content-type, x-app-token');
for(const headers of ['authorization','x-app-token,x-app-token','',Array(201).fill('a').join('')])assert.equal(call(p,'https://fixture.example','OPTIONS',{'access-control-request-method':'POST','access-control-request-headers':headers}).result.status,403);
assert.equal(call(p,'https://fixture.example','OPTIONS',{'access-control-request-method':'DELETE'}).result.status,403);assert.equal(call(p,undefined,'OPTIONS').result.status,403);
for(const s of ['*','http://fixture.example','https://fixture.example/','https://Fixture.example','https://user@fixture.example','https://fixture.example,https://fixture.example',' https://fixture.example'])assert.throws(()=>policy(s));
console.log('empty-deny exact Origin duplicate/null/no-origin preflight/canonical/credentials absent PASS');
const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function server(){let handler,fetches=0;const ctx={require:n=>n==='http'?{createServer:f=>{handler=f;return{listen(){}};}}:require(path.resolve(__dirname,'../..',n)),process:{env:{APP_SECRET:'public-fixture',GROQ_KEYS:'fixture',PROXY_ALLOWED_ORIGINS:'https://fixture.example'},on(){},exit(){}},Buffer,ArrayBuffer,setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},console:{log(){},warn(){}},Date,URL,AbortController,fetch:async()=>{fetches++;return{status:401,headers:{get:()=>null},text:async()=>'{}'};}};vm.runInNewContext(fs.readFileSync(path.resolve(__dirname,'../../proxy.js'),'utf8'),ctx);return{handler,count:()=>fetches};}
async function request(s,origin,method='POST',url='/groq/openai/v1/chat/completions',extra={}){let status,body,end,headers={};const req={method,url,headers:{'x-app-token':'public-fixture',...extra,...(origin===undefined?{}:{origin})},rawHeaders:[],socket:{remoteAddress:'192.0.2.1'},on(n,f){if(n==='end')end=f;},destroy(){throw Error('destroy');}};await s.handler(req,{setHeader:(k,v)=>headers[k]=v,writeHead(c,h){status=c;Object.assign(headers,h);},end(x){body=x;}});if(end)await end();return{status,body,headers};}
(async()=>{const s=server();assert.equal((await request(s,'https://evil.example')).status,403);assert.equal(s.count(),0);let r=await request(s,'https://fixture.example');assert.equal(r.status,401);assert.equal(s.count(),1);assert.equal(r.headers['Access-Control-Allow-Origin'],'https://fixture.example');assert.notEqual(r.headers['Access-Control-Allow-Origin'],'*');r=await request(s,undefined,'GET','/health');assert.equal(r.status,200);assert.equal(r.headers['Access-Control-Allow-Origin'],undefined);r=await request(s,'https://fixture.example','OPTIONS','/groq/openai/v1/chat/completions',{'access-control-request-method':'POST','access-control-request-headers':'x-app-token'});assert.equal(r.status,204);assert.equal(s.count(),1);console.log('proxy integration denies before upstream, provider response exactreflect/nooverride, noOrigin health, preflight zero provider PASS');})().catch(e=>{console.error(e);process.exitCode=1;});
