'use strict';
const assert=require('node:assert/strict');const {createLifecycle}=require('../../proxy_runtime/lifecycle.cjs');
function fixture(decode=async x=>x){let now=0,id=0,sockets=[],timers=new Map(),messages=[],states=[];
 const c=createLifecycle({makeSocket:()=>{const s={closed:0,close(){this.closed++;}};sockets.push(s);return s;},subscribe:()=>{},decode,onMessage:x=>messages.push(x),onState:x=>states.push(x),setTimer:(f,d)=>{timers.set(++id,{f,d});return id;},clearTimer:i=>timers.delete(i),clock:()=>now});
 return {c,sockets,timers,messages,states,setNow:x=>now=x,fire:()=>{const [k,v]=timers.entries().next().value;timers.delete(k);v.f();}};
}
(async()=>{let tests=0;async function test(n,f){await f();tests++;console.log('PASS',n);}
 await test('replace closes old and stale events cannot retry',()=>{const f=fixture();f.c.connect();let s=f.sockets[0];const close=s.onclose,open=s.onopen;f.c.connect();assert.equal(s.closed,1);close();open();assert.equal(f.timers.size,1);assert.equal(f.sockets.length,2);});
 await test('error+close single retry, reconnect cancels pending',()=>{const f=fixture();f.c.connect();const s=f.sockets[0],close=s.onclose,error=s.onerror;error();close();assert.equal(f.timers.size,1);f.c.connect();assert.equal(f.timers.size,1);assert.equal(s.closed,1);});
 await test('watchdog owns one active socket incl quiet from open',()=>{const f=fixture();f.c.connect();f.sockets[0].onopen();f.setNow(360000);assert(f.c.watchdog());assert.equal(f.sockets[0].closed,1);assert.equal(f.sockets.length,1);assert(f.c.snapshot().retryPending);assert(!f.c.snapshot().connected);});
 await test('async stale decode never publishes',async()=>{let resolve;const f=fixture(()=>new Promise(r=>resolve=r));f.c.connect();const pending=f.sockets[0].onmessage('old');await Promise.resolve();f.c.connect();resolve('decoded');await pending;assert.equal(f.messages.length,0);});
 await test('retry resets only on open and shutdown cancels all',()=>{const f=fixture();f.c.connect();f.sockets[0].onclose();f.fire();assert.equal(f.sockets.length,2);f.sockets[1].onopen();f.sockets[1].onerror();assert.equal([...f.timers.values()][0].d,1000);f.c.shutdown();assert.equal(f.timers.size,0);assert(!f.c.connect());assert(!f.c.snapshot().socketOwned);assert(f.sockets.every(s=>s.closed===1));});
 await test('create/subscribe failure safely closes and retries',()=>{let closed=0,timers=0;const s={close:()=>closed++};const c=createLifecycle({makeSocket:()=>s,subscribe:()=>{throw Error('x');},decode:async x=>x,onMessage:()=>{},setTimer:()=>++timers,clearTimer:()=>{},clock:()=>0});c.connect();s.onopen();assert.equal(closed,1);assert(c.snapshot().retryPending);c.shutdown();});
 await test('hung handshake drops and retries',()=>{const f=fixture();f.c.connect();f.fire();assert.equal(f.sockets[0].closed,1);assert(f.c.snapshot().retryPending);assert.equal(typeof f.sockets[0].onerror,'function');});
 await test('invalid open clock refuses',()=>{const f=fixture();f.c.connect();f.setNow(NaN);f.sockets[0].onopen();assert.equal(f.sockets[0].closed,1);assert(!f.c.snapshot().connected);});
 await test('decode flood bounded and old decode fenced',async()=>{let resolve;const f=fixture(()=>new Promise(r=>resolve=r));f.c.connect();const pending=f.sockets[0].onmessage('first');await Promise.resolve();for(let i=0;i<17;i++)f.sockets[0].onmessage('queued');assert.equal(f.sockets[0].closed,1);assert(f.c.snapshot().retryPending);resolve('old');await pending;assert.equal(f.messages.length,0);});
 await test('EventEmitter late error retained after detach',()=>{const {EventEmitter}=require('node:events');let ws;const c=createLifecycle({makeSocket:()=>{ws=new EventEmitter();ws.close=()=>{};return ws;},subscribe:()=>{},decode:async x=>x,onMessage:()=>{},setTimer:()=>1,clearTimer:()=>{}});c.connect();c.shutdown();assert.doesNotThrow(()=>ws.emit('error',Error('late')));});
 await test('reconnect recovers stalled decode slot',async()=>{const f=fixture(x=>x==='stuck'?new Promise(()=>{}):Promise.resolve(x));f.c.connect();const old=f.sockets[0].onmessage('stuck');await Promise.resolve();f.c.connect();f.sockets[1].onopen();f.sockets[1].onmessage('new');await old;await new Promise(r=>setImmediate(r));assert.deepEqual(f.messages,['new']);f.c.shutdown();});
 await test('decode deadline drops stalled generation',async()=>{const f=fixture(()=>new Promise(()=>{}));f.c.connect();f.sockets[0].onopen();const pending=f.sockets[0].onmessage('stuck');await Promise.resolve();f.fire();await pending;assert.equal(f.sockets[0].closed,1);assert(f.c.snapshot().retryPending);});
 console.log(tests+' tests passed');})().catch(e=>{console.error(e);process.exitCode=1;});
